### ISSUE TITLE
    java.lang.AbstractMethodError: abstract method not implemented

### ISSUE THREAD

**Issue by santoshgistto** [firebase/geofire-java#10]
Process: com.firebase.sfvehicles, PID: 16873
    java.lang.AbstractMethodError: abstract method not implemented
            at com.firebase.client.android.AndroidPlatform.newRunLoop(AndroidPlatform.java)
            at com.firebase.client.core.Context.ensureRunLoop(Context.java:219)
            at com.firebase.client.core.Context.initServices(Context.java:106)
            at com.firebase.client.core.Context.freeze(Context.java:87)
            at com.firebase.client.core.RepoManager.getLocalRepo(RepoManager.java:55)
            at com.firebase.client.core.RepoManager.getRepo(RepoManager.java:19)
            at com.firebase.client.Firebase.<init>(Firebase.java:182)
            at com.firebase.client.Firebase.<init>(Firebase.java:187)
            at com.firebase.client.Firebase.<init>(Firebase.java:165)
            at com.firebase.sfvehicles.SFVehiclesActivity.onCreate(SFVehiclesActivity.java:56)
            at android.app.Activity.performCreate(Activity.java:5584)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
            at android.app.ActivityThread.access$900(ActivityThread.java:171)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jdimond** [comment]
There is a dependency mismatch here. geofire depends on firebase-client-jvm in version 2.2 but firebase-client-android depends on firebase-client-jvm 2.3. If you include firebase-client-jvm explicitly in version 2.2 this will be resolved. We already have a PR merged that fixes the dependency in the pom, but didn't get around to release a new version yet

**Comment by santoshgistto** [comment]
thanks working
