### ISSUE TITLE
I have issues with GeoFire 2.3.0

### ISSUE THREAD

**Issue by DongNH4** [firebase/geofire-java#133]
I just upgraded GeoFire android from 2.2.0 to 2.3.0.
I noticed my app was stopped.
This is my log : 
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: com.google.firebase.database.DatabaseReference.setValue
        at com.firebase.geofire.GeoFire.removeLocation(GeoFire.java:215)
        at com.firebase.geofire.GeoFire.removeLocation(GeoFire.java:192)

But, in version 2.2.0, it work fine.
Please help me.

**Comment by psteiger** [comment]
I'm experiencing the same issue.

**Comment by samtstern** [comment]
Consolidating this into #28 which looks the same to me.

**Comment by Ahmedomarpro** [comment]
2019-05-22 08:56:37.712 25317-25317/com.coco.uber_part E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.coco.uber_part, PID: 25317
    java.lang.NoSuchMethodError: No virtual method setValue(Ljava/lang/Object;Ljava/lang/Object;)Lcom/google/firebase/tasks/Task; in class Lcom/google/firebase/database/DatabaseReference; or its super classes (declaration of 'com.google.firebase.database.DatabaseReference' appears in /data/app/com.coco.uber_part-T0zswnb00WefX14JZqrmOw==/base.apk)
        at com.firebase.geofire.GeoFire.setLocation(GeoFire.java:182)
        at com.firebase.geofire.GeoFire.setLocation(GeoFire.java:154)
        at com.coco.uber_part.CostumerMapActivity$2.onClick(CostumerMapActivity.java:102)
        at android.view.View.performClick(View.java:6311)
        at android.view.View$PerformClick.run(View.java:24996)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
-------------------------------------

1. It will work fine if you add a listener in its parameters.As
2. check firebase auth Email  

** Solve the problem

    private GeoFire geoFire;
geoFire = new GeoFire(database.getReference().child("geofire_location"));

 String key = geoFire.getDatabaseReference().push().getKey();
 geoFire.setLocation(key,new GeoLocation(37.7789, -122.4017)),new 
 GeoFire.CompletionListener(){
            @Override
            public void onComplete(String key, DatabaseError error) {
                //Do some stuff if you want to
            }
        });

**Comment by mudebbela** [comment]
@Ahmedomarpro your solution works this works, but to the developers, this is still a bug right?
