### ISSUE TITLE
Got Datasnapshot without location with key. kindly look into it.

### ISSUE THREAD

**Issue by naumanmir** [firebase/geofire-java#140]
java.lang.AssertionError: Got Datasnapshot without location with key vcMAoYmFgLbfmnjop69OemcGYfk2
        at com.firebase.geofire.GeoQuery.childAdded(GeoQuery.java:285)
        at com.firebase.geofire.GeoQuery.access$000(GeoQuery.java:51)
        at com.firebase.geofire.GeoQuery$1.onChildAdded(GeoQuery.java:72)
        at com.google.android.gms.internal.zzecw.zza(Unknown Source)
        at com.google.android.gms.internal.zzeia.zzbyc(Unknown Source)
        at com.google.android.gms.internal.zzeig.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:211)
        at android.app.ActivityThread.main(ActivityThread.java:5323)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by samtstern** [comment]
@naumanmir can you show the code for how you're adding locations with GeoFire? Are you putting locations in the same node as your data?

**Comment by pandalion98** [comment]
Here's what I found:

The error happens when, in the database location, there is a valid Geohash `g` but no location data `l`. To prevent this error, you will need to guarantee that if you store a valid Geohash, you also have a valid location.

**For those who place their coordinates and Geohash "manually" into Firebase**, the error happens when you put them in _one at a time_, and especially when `g` goes first. As in:
```
dbReference.child("g").setValue(geohash.toString());
dbReference.child("l").child("0").setValue(latitude);
dbReference.child("l").child("1").setValue(longitude);
```

To fix the issue, you need to place your data into Firebase _together_, or at least make sure `g` is last. The best method would be to do it [as Geofire does](https://github.com/firebase/geofire-java/blob/c46ff339060d150741a8d0d40c8e73b78edca6c3/common/src/main/java/com/firebase/geofire/GeoFire.java#L165) by using a HashMap:

```
Map<String, Object> updates = new HashMap<>();
updates.put("g", geohash.toString());
updates.put("l", Arrays.asList(latitude, longitude));

dbReference.setValue(updates);
```

I recommend this issue be closed.

**Comment by samtstern** [comment]
Thanks @pandalion98 !  Since there has been no other response in a while, I agree that we can blame this on inconsistent data and close the issue.
